apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-keycloak
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend-keycloak
  template:
    metadata:
      labels:
        app: backend-keycloak
    spec:
      containers:
      - name: backend-keycloak
        image: ghcr.io/kyleee0522/springboot_crud_security_keycloak:v5
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prd"
          - name: APP_CORS_ALLOWED_ORIGINS            
            value: "frontend"
          - name: SERVER_PORT            
            value: "8080" 
        ports:
        - containerPort: 8080
